[[Snowball]]
arch = "aarch64"
git-tree-sha1 = "65625e7aab15beb3a47668553cb09a617e57e472"
os = "macos"

    [[Snowball.download]]
    sha256 = "1ab2854b767c41239e494f563e65d926f1072620f8d43c94afecb93938c2a57f"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.aarch64-apple-darwin.tar.gz"
[[Snowball]]
arch = "aarch64"
git-tree-sha1 = "170857abe0280df4034c5412a43224ea7b07dce7"
libc = "glibc"
os = "linux"

    [[Snowball.download]]
    sha256 = "2e9f867e3e1344956ae45a6e8f24ec522b3d9a8ae3be6bbec3c13bdf3f3682d5"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.aarch64-linux-gnu.tar.gz"
[[Snowball]]
arch = "aarch64"
git-tree-sha1 = "c4acb74bd896915181d3eeeaf3eebb0b89366b24"
libc = "musl"
os = "linux"

    [[Snowball.download]]
    sha256 = "9c0403135ca4c70c9d63bce96c27c0f003f5ce1a7f42c91bd48566072355ce27"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.aarch64-linux-musl.tar.gz"
[[Snowball]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "569b7697bad4fd5d1380650f6a2d3b35996d2913"
libc = "glibc"
os = "linux"

    [[Snowball.download]]
    sha256 = "ed69c48b7a8e66bdbf8a301c3c122baec9f96450ce382813f59ab8941676aa77"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.armv6l-linux-gnueabihf.tar.gz"
[[Snowball]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b45a3d27778a74c5f469000c9a451fc095c11b13"
libc = "musl"
os = "linux"

    [[Snowball.download]]
    sha256 = "04cfe87143301768193923e58a60a8059ac5fe40d702a62cd4c3b870f9a24a4b"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.armv6l-linux-musleabihf.tar.gz"
[[Snowball]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81d35d3d4a5241764ca4942ef0d5cbb6606a30fd"
libc = "glibc"
os = "linux"

    [[Snowball.download]]
    sha256 = "29af8dbd73a623d75628f4423b8114e16fe68f011a26b17207d050becd494026"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[Snowball]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c7b42dc3e64078ce7595d6f05784840cce8f0d7"
libc = "musl"
os = "linux"

    [[Snowball.download]]
    sha256 = "e1c17acd37a17621a9011efcaa87c20a4553bc3fa71e9691e8a1727b9a84ff78"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[Snowball]]
arch = "i686"
git-tree-sha1 = "c3b91842abb93d6f11a9dfbc365f077c39f05e4d"
libc = "glibc"
os = "linux"

    [[Snowball.download]]
    sha256 = "e1b88bcfc82769841d98f9eb726c8cdc8dbfc0bc64a550b69c55bc43dbd54339"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.i686-linux-gnu.tar.gz"
[[Snowball]]
arch = "i686"
git-tree-sha1 = "19f687cfd8a063bdea7d0dc8d0436c261d61e970"
libc = "musl"
os = "linux"

    [[Snowball.download]]
    sha256 = "3d285bad78345a9443da5c3b8731f9b07e1416d393f22be108eb9f0fa4832963"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.i686-linux-musl.tar.gz"
[[Snowball]]
arch = "i686"
git-tree-sha1 = "ff136bb4dbec24803978ff8ba9748d00d94120a3"
os = "windows"

    [[Snowball.download]]
    sha256 = "dee8c240e29dd47221991623521489e25cbd4b331a5f2d28a876bf37c5b823d7"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.i686-w64-mingw32.tar.gz"
[[Snowball]]
arch = "powerpc64le"
git-tree-sha1 = "d36f18c813b7f7ca6a701f5c6801d93a98219c25"
libc = "glibc"
os = "linux"

    [[Snowball.download]]
    sha256 = "00791f76836730f037221682da2d5c198aec98117bebf99b217ea0fedac7b513"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[Snowball]]
arch = "x86_64"
git-tree-sha1 = "157afd7c085217fe7c2074cce870659638d24e55"
os = "macos"

    [[Snowball.download]]
    sha256 = "bf1b75d50bd4ae7df86dd0f4c5d9e65ac353d04caa5667a898fb54dce8186c15"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.x86_64-apple-darwin.tar.gz"
[[Snowball]]
arch = "x86_64"
git-tree-sha1 = "ffc21d4e086ecfaa3db52fc84bcac85f657bcad1"
libc = "glibc"
os = "linux"

    [[Snowball.download]]
    sha256 = "8ca3bf0741fc9fb57f5e4b9d3e9cbd68e4243398bb0e0b5e4de9487c27a1408b"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.x86_64-linux-gnu.tar.gz"
[[Snowball]]
arch = "x86_64"
git-tree-sha1 = "4d39e5b29447eaa586b3ab548b3b0b9d8491ce83"
libc = "musl"
os = "linux"

    [[Snowball.download]]
    sha256 = "e3b186230e9046faef9bf12776d26fbec8ac9f966bc041c35a15cdef1a41e223"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.x86_64-linux-musl.tar.gz"
[[Snowball]]
arch = "x86_64"
git-tree-sha1 = "ceb8718f77d6a06a35abaad9d7307f5bfa40f296"
os = "freebsd"

    [[Snowball.download]]
    sha256 = "42655d7cda75a8039999b38df6700a7591d18a36a80968cb23dbba1f847b0db5"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[Snowball]]
arch = "x86_64"
git-tree-sha1 = "dad63afc19a4bdfecfbd25ac304f4e5fe0577e4f"
os = "windows"

    [[Snowball.download]]
    sha256 = "916eb891b9c3c0dfeac2b0465c9f31f1e00969c2490451d5b8b2fffc566fb49f"
    url = "https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases/download/Snowball-v2.2.0+0/Snowball.v2.2.0.x86_64-w64-mingw32.tar.gz"
