# Autogenerated wrapper script for Snowball_jll for i686-w64-mingw32
export libstemmer

JLLWrappers.@generate_wrapper_header("Snowball")
JLLWrappers.@declare_library_product(libstemmer, "libstemmer.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstemmer,
        "bin\\libstemmer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
