# Autogenerated wrapper script for Snowball_jll for x86_64-unknown-freebsd
export libstemmer

JLLWrappers.@generate_wrapper_header("Snowball")
JLLWrappers.@declare_library_product(libstemmer, "libstemmer.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstemmer,
        "lib/libstemmer.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
