# Autogenerated wrapper script for Snowball_jll for x86_64-apple-darwin
export libstemmer

JLLWrappers.@generate_wrapper_header("Snowball")
JLLWrappers.@declare_library_product(libstemmer, "@rpath/libstemmer.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstemmer,
        "lib/libstemmer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
